@startuml
title 游戏社区用户管理系统活动图

start
:系统启动;

if (用户身份是系统管理员?) then (是)
    :配置系统基础设置（如权限等）;
    :录入用户信息;
    :录入游戏信息;
    :维护系统数据（定期更新等）;
else if (用户身份是社区管理员?) then (是)
    :查看普通用户/游戏信息;
    if (检测游戏内容是否存在违规) then (是)
        :对违规内容进行修改;
    endif
    if (验证用户评论/上传内容是否违规) then (是)
        :对上传内容即用户进行违规处理;
    endif
    :查看游戏社区板块评估;
else (用户身份是普通用户?)
    :登录系统;
    :查看个人信息/游戏社区;
    if (需要添加游戏入库?) then (是)
        :申请添加所需游戏并提交;
    endif
    if (想查看个人游戏库存?) then (是)
        :查看个人游戏库存;
    endif
endif

stop
@enduml