@startuml
actor "社区用户" as employee
actor "账户数据库" as department_manager
actor "系统管理员" as hr_specialist
actor "社区管理员" as system_admin

employee -> "用户管理系统" : 登录/注册系统
employee -> "用户管理系统" : 上线
employee -> "用户管理系统" : 下线
"用户管理系统" -> department_manager : 推送申请验证
department_manager -> "用户管理系统" : 查看申请详情
department_manager -> "用户管理系统" : 验证申请（同意/拒绝）
"用户管理系统" -> employee : 通知申请验证结果

employee -> "用户管理系统" : 编辑个人信息
employee -> "用户管理系统" : 提交信息更新请求
"用户管理系统" -> hr_specialist : 推送信息更新请求
hr_specialist -> "用户管理系统" : 审核更新内容
hr_specialist -> "用户管理系统" : 根据审核情况完成信息更新

system_admin -> "用户管理系统" : 登录系统
system_admin -> "用户管理系统" : 选择需设置权限的用户
system_admin -> "用户管理系统" : 根据情况调整权限内容
"用户管理系统" -> system_admin : 确认权限设置成功

employee -> "用户管理系统" : 查看验证结果
"用户管理系统" -> employee : 显示验证详情

employee -> "用户管理系统" : 进入游戏社区
"用户管理系统" -> hr_specialist : 推送用户个人消息
hr_specialist -> "用户管理系统" : 验证账户情况
hr_specialist -> "用户管理系统" : 根据审核情况确认是/否同意进入社区
"用户管理系统" -> employee : 推送社区内容
@enduml