@startuml
'定义员工类
class 展示板块 {
    - 游戏编号: int
    - 游戏名称: String
    - 适合年龄: int
    - 内容标签: String
    + 获取游戏信息(): String
    + 设置游戏信息(游戏名称: String, 适合年龄: int, 内容标签: String): void
}

'定义部门类
class 玩家用户 {
    - 用户编号: int
    - 用户名称: String
    - 用户年龄: int
    + 添加喜好(标签/游戏): void
    + 移除喜好(标签/游戏): void
    + 获取游戏信息(): String
}

'定义职位类
class 管理员 {
    - 职位编号: int
    - 职位名称: String
    - 职位描述: String
    + 编辑游戏展示内容(游戏内容): void
    + 获取管理员信息(): String
}

'定义各类之间的关系
展示板块 "1" *-- "0..*" 管理员 : 编辑
展示板块 "1" *-- "0..1" 玩家用户 : 评价
玩家用户 "1" *-- "0..*" 展示板块 : 展示
管理员 "1" *-- "0..*" 展示板块 : 反馈
@enduml