@startuml
left to right direction
package "游戏社区管理系统" {
    component "用户基本信息数据库" as DB1
    component "游戏数据库" as DB2
    component "游戏内容数据库" as DB3
    component "用户界面" as UI
    component "用户信息展示管理模块" as BL1
    component "搜素模块" as BL2
    component "游戏社区展示模块" as BL3
}

UI --> BL1 : 个人信息展示操作请求
UI --> BL2 : 搜索游戏相关操作请求
UI --> BL3 : 进入主页相关操作请求

BL1 --> DB1 : 读写基本信息
BL2 --> DB2 : 读写游戏数据
BL2 --> BL1 : 添加游戏信息
BL3 --> DB3 : 读写内容展示数据
BL3 --> BL1 : 添加游戏信息
BL3 --> BL2 : 搜索游戏

@enduml